application: direct-mission-95122
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app
- url: /
  static_files: web_static/index.html
  upload: web_static/index.html
- url: /(.*)
  static_files: web_static/\1
  upload: web_static/(.*)
skip_files:
- ^/web-front/.*
